MAIN=main
CPU=LucasFirmoCpu
BUTTON=LucasFirmoButton
DISPLAY=LucasFirmoDisplay
KEYBOARD=LucasFirmoKeyboard
BTNULL=LucasFirmoButtonNull

all:
	g++ $(MAIN).cpp $(CPU).cpp $(BUTTON).cpp $(DISPLAY).cpp $(KEYBOARD).cpp $(BTNULL).cpp
	g++ -o main *.o